# Alertmanager web configuration for TLS and basic auth
# Used by the alertmanager-secure container
tls_server_config:
  cert_file: /etc/certs/server.pem
  key_file: /etc/certs/server-key.pem

# Basic auth credentials
# Username: admin
# Password: password (hashed with bcrypt)
basic_auth_users:
  admin: $2y$05$557VESWA3feQTNHuPdQuiOM8b9Y6Vy6WsDxLUBQHjSvtP8udWiAq2
